[[docs]]
  name = "关于重力中国"
  weight = 1
  identifier = "about"
  url = "/about/"

[[docs]]
  name = "重力学入门"
  weight = 5
  identifier = "getting-started"
  url = "/getting-started/"

[[docs]]
  name = "重力软件教程"
  weight = 15
#  identifier = "modules"
  post = "break"
  url = "/gravity-manual/"

# Core Menus


[[docs]]
  name = "重力数据处理教程"
  weight = 35
#  identifier = "variables"
  url = "/gravitydata/"
[[docs]]
  name = "重力开源软件开发"
  weight = 36
  identifier = "pipes"
  url = "/gravity-software/"


# LOW LEVEL ITEMS

[[docs]]
  name = "重力项目展示"
  weight = 70
#  identifier = "tools"
  url = "/gravity-projects/"

[[docs]]
  name = "编程教程"
  weight = 80
#  identifier = "hosting-and-deployment"
  url = "/coding/"

[[docs]]
  name = "贡献指南"
  weight = 100
  post = "break"
#  identifier = "contribute"
  url = "/contribute/"

# [[docs]]
#   name = "Categories"
#   weight = 140
#   identifier = "categories"
#   url = "/categories/"


######## GLOBAL ITEMS TO BE SHARED WITH THE HUGO SITES

[[global]]
    name = "新闻"
    weight = 1
    identifier = "news"
    url = "/news/"

  [[global]]
    name = "文档"
    weight = 5
    identifier = "docs"
    url = "/documentation/"

  [[global]]
    name = "关于我们"
    weight = 300
    identifier = "themes"
    url = "/about/"

    [[global]]
      name = "研究案例"
      weight = 20
      identifier = "showcase"
      url = "/gravity-projects/"

  # Anything with a weight > 100 gets an external icon
  [[global]]
    name = "重力论坛"
    weight = 150
    icon = true
    identifier = "community"
    post = "external"
    url = "https://discourse.gravitychina.ga/"


  [[global]]
    name = "GitHub"
    weight = 200
    identifier = "github"
    post = "external"
    url = "https://github.com/Gravity-Geodesy-China-Community"